name: cruise
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  sizer: ^2.0.15
  provider: ^6.0.5
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  google_maps_flutter: ^2.5.0
  dio: ^5.3.2
  flutter_polyline_points: ^2.0.0
  geolocator: ^10.0.1
  readmore: ^2.2.0
  qr_flutter: ^4.1.0
  image_picker: ^1.0.4
  fl_chart: ^0.64.0
  shimmer: ^3.0.0
  lottie: ^2.6.0
  intl: ^0.18.1
  grouped_list: ^5.1.2
  geocoding: ^2.1.1
  http: ^1.1.0
  url_launcher: ^6.1.14
  flutter_barcode_scanner: ^2.0.0
  timeago: ^3.5.0
  fluttertoast: ^8.2.2
  flutter_local_notifications: ^16.1.0
  encrypt: ^5.0.3
  
  # firebase packages
  cloud_firestore: ^4.12.1
  firebase_core: ^2.20.0
  firebase_messaging: ^14.7.2
  firebase_storage: ^11.4.0
  firebase_auth: ^4.12.0
  cloud_functions: ^4.5.2
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^6.0.2
  change_app_package_name: ^1.1.0
  twitter_login: ^4.4.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/cruise.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/icons/tickets.png

  android_12:
    image: assets/icons/tickets_white.png
    icon_background_color: "#000142"

flutter:
  uses-material-design: true


  assets:
    - assets/icons/
    - assets/image/
    - assets/map/
    - assets/lottie/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 300
