// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI8mXdMTGwVsUsgpaIZJPVrZnM4SZariU',
    appId: '1:499467873123:android:36129f4a09ffd3a19bc156',
    messagingSenderId: '499467873123',
    projectId: 'cruise-ticketing',
    storageBucket: 'cruise-ticketing.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcVITEfUMqAjB3rbY5W2r_vQKpJiLnRUo',
    appId: '1:499467873123:ios:9ad86eeb32ce118a9bc156',
    messagingSenderId: '499467873123',
    projectId: 'cruise-ticketing',
    storageBucket: 'cruise-ticketing.appspot.com',
    androidClientId: '499467873123-50btahkf0edhikgvbt47t7qb7cq54qcc.apps.googleusercontent.com',
    iosClientId: '499467873123-mc5kk7u08ffmrob7jn0g16s3kasuthkd.apps.googleusercontent.com',
    iosBundleId: 'com.example.cruise',
  );
}
